site_name: VM Operator
site_url: https://github.com/vmware-tanzu/vm-operator
repo_url: https://github.com/vmware-tanzu/vm-operator
edit_uri: blob/main/docs/
docs_dir: docs
site_dir: .site

theme:
  name: material
  custom_dir: docs/www/themes/material

  favicon: favicon.svg
  icon:
    logo: vm-op/logo-white-solid

  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

  features:
  - content.code.annotate
  - content.code.copy

extra_css:
- www/css/vm-operator.css
- www/css/vm-operator-font.css

#extra:
  # TODO(akutz) Get this working with RTFD
  # version:
  #   default: latest
  #   provider: mike

markdown_extensions:
- admonition
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
    options:
      custom_icons:
      - material/.icons
- pymdownx.inlinehilite
- pymdownx.highlight:
    use_pygments: true
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.details
- tables
- attr_list
- md_in_html

nav:
- Home: index.md
- User Guide:
  - Deploy a VM: user-guide/deployvm.md
  # - Platforms:
  #   - Overview: user-guide/platforms.md
  #   - Supervisor: user-guide/platforms/supervisor.md
  # - Help:
  #   - Troubleshooting: user-guide/help/troubleshooting.md
  #   - Usage: user-guide/help/usage.md
- Developer Guide:
  - Project Guidelines: dev-guide/project-guidelines.md
  - Build Reference: dev-guide/build-reference.md
  - Release Process: dev-guide/release-process.md
- API Reference:
  - Overview: apis/overview.md
  - v1alpha1: apis/v1alpha1.md
- About:
  - Contributing: about/contributing.md
  - License: about/license.md
  - Release Notes: about/release-notes.md
