apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: 2018-12-16T19:42:03Z
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: vmoperator
  resourceVersion: "323"
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/edit
  uid: a95c7bff-016a-11e9-aa16-0800278b6504
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/exec
  - pods/portforward
  - pods/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  - services/proxy
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - bindings
  - events
  - limitranges
  - namespaces/status
  - pods/log
  - pods/status
  - replicationcontrollers/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
- apiGroups:
  - "apps"
  - "extensions"
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "vmoperator.vmware.com"
  resources:
  - virtualmachines
  - virtualmachineimages
  verbs:
  - get
  - list
  - watch
  - update
  - patch
