apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmoperator-apiserver
spec:
  template:
    spec:
       affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: app
                 operator: In
                 values:
                 - vmop
             topologyKey: "kubernetes.io/hostname"