# Adds namespace to all resources. Note: WCP treats vmware-system-* namespaces as reserved so we need that prefix
namespace: vmware-system-vmop

bases:
  - ../rbac
  - ../apiserver
  - ../manager

images:
  - name: vmoperator:latest
    newName: vmware/vmop
    newTag: 0.0.1

resources:
  - namespace.yaml
  - rbac_psp.yaml
  - endpoints.yaml
  - vsphere_provider_config.yaml

patchesStrategicMerge:
  - master_node_selector_patch.yaml
  - master_toleration_patch.yaml
  - apiservice_namespace_patch.yaml
  - apiserver_service_patch.yaml
  - apiserver_deployment_patch.yaml
  - controller_deployment_patch.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: vmoperator
    path: apiserver_service_remove_selector.yaml
