# Adds namespace to all resources. Note: WCP treats vmware-system-* namespaces as reserved so we need that prefix
namespace: vmware-system-vmop

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: vmware-system-vmop-

bases:
  - ../rbac
  - ../apiserver
  - ../manager

images:
  - name: vmoperator:latest
    newName: vmware/vmop
    newTag: 0.0.1

patchesStrategicMerge:
  - master_node_selector_patch.yaml
  - master_toleration_patch.yaml
  - apiservice_namespace_patch.yaml
  - apiserver_service_patch.yaml
  - apiserver_patch.yaml
  - controller_patch.yaml

resources:
  - rbac_psp.yaml
  - endpoints.yaml
