# Bind the PSP Role to the VM Operator to allow access to host networking
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wcp-vmware-system-vmop:psp
  namespace: vmware-system-vmop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wcp-privileged-psp
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:vmware-system-vmop
