apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere.provider.config.vmoperator.vmware.com
  namespace: vmware-system-vmop
data:
  VcPNID: <vc_pnid>
  VcCredsSecretName: wcp-vmop-sa-vc-auth
  Datacenter: <datacenter>
  StorageClassRequired: "true"
  # TODO: Update this before we ship 1.0
  ContentSource: Kubernetes
