apiVersion: v1
kind: ConfigMap
metadata:
  name: vsphere.provider.config.vmoperator.vmware.com
  namespace: vmware-system-vmop
data:
  VcPNID: <vc_pnid>
  VcCredsSecretName: wcp-vmop-sa-vc-auth
  Datacenter: <datacenter>
  # TODO: Uncomment the next line and remove datastore config after is done
  #  StorageClassRequired: true
  Datastore: nfs0-1
  # TODO: Update this before we ship 1.0
  ContentSource: Kubernetes

