name: notify-gchat-on-issue
on:
  issues:
    types:
    - opened
    - closed
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Google Chat Notification
      env:
        GOOGLE_SPACE_URL: ${{ secrets.GOOGLE_SPACE_URL }}
        GITHUB_THREAD_KEY: ${{ github.event.issue.number }}
        GITHUB_EVENT_NUMBER: ${{ github.event.issue.number }}
        GITHUB_EVENT_STATE: ${{ github.event.issue.state }}
        GITHUB_EVENT_TITLE: ${{ github.event.issue.title }}
        GITHUB_EVENT_USER: ${{ github.event.issue.user.login }}
        GITHUB_EVENT_URL: ${{ github.event.issue.html_url }}
        GITHUB_EVENT_LABELS: ${{ join(github.event.issue.labels.*.name) }}
        GITHUB_EVENT_ASSIGNEES: ${{ join(github.event.issue.assignees.*.login) }}
      run: |
        curl --location --request POST "${GOOGLE_SPACE_URL}&messageReplyOption=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD" \
        --header 'Content-Type: application/json' \
        --data-raw '{
            "thread": {"threadKey": "'"${GITHUB_THREAD_KEY}"'"},
            "cards": [
              {
                "header": {
                  "title": "Issue Tracker",
                  "subtitle": "Issue No: #'"${GITHUB_EVENT_NUMBER}"'"
                },
                "sections": [
                  {
                    "widgets": [
                      {
                        "keyValue": {
                          "topLabel": "Creator",
                          "content": "'"${GITHUB_EVENT_USER}"'"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Title",
                          "content": "'"${GITHUB_EVENT_TITLE}"'"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "State",
                          "content": "'"${GITHUB_EVENT_STATE}"'"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Labels",
                          "content": "- '"${GITHUB_EVENT_LABELS}"'"
                        }
                      },
                      {
                        "keyValue": {
                          "topLabel": "Assignees",
                          "content": "- '"${GITHUB_EVENT_ASSIGNEES}"'"
                        }
                      },
                      {
                        "buttons": [
                          {
                            "textButton": {
                              "text": "OPEN ISSUE",
                              "onClick": {
                                "openLink": {
                                  "url": "'"${GITHUB_EVENT_URL}"'"
                                }
                              }
                            }
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }'
